# AUTOGENERATED! DO NOT EDIT! File to edit: gradio.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'intf', 'classify_image']

# %% gradio.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% gradio.ipynb 4
learn = load_learner('training_export/export.pkl')

# %% gradio.ipynb 6
categories = ('Chaya plant', 'Papaya fruit', 'Papaya plant')
def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% gradio.ipynb 8
image = gr.components.Image(width=192,height=192)
label = gr.components.Label()

intf = gr.Interface(fn=classify_image, inputs = image, outputs = label, examples = exampleImagesList)
intf.launch(inline=False)
